[package]
name = "prime_fact"
version = "0.1.0"
authors = ["Emīls Piņķis <pinkisemils@gmail.com>"]

[dependencies]
num = "0.1"
num_cpus = "1.1.0"
rayon = "0.6"
itertools = "0.5.9"
linked-hash-map = "0.4.1"
